### np.sort

return a sorted of an array.


In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([48, 75, 23, 77, 16,  6, 89, 30, 40, 29, 60, 47, 88, 84, 48])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[45, 35, 84, 75],
       [68, 50, 32, 10],
       [42, 68, 42, 41],
       [88, 48, 37, 52],
       [70, 69, 82, 70],
       [91, 54, 16, 68]])

In [7]:
np.sort(a)[::-1]

array([89, 88, 84, 77, 75, 60, 48, 48, 47, 40, 30, 29, 23, 16,  6])

In [6]:
np.sort(b,axis=0)

array([[42, 35, 16, 10],
       [45, 48, 32, 41],
       [68, 50, 37, 52],
       [70, 54, 42, 68],
       [88, 68, 82, 70],
       [91, 69, 84, 75]])

### np.append

The numpy.append() appends values along the mentioned axis a t the end of the array


In [9]:
# code
np.append(a,200)

array([ 48,  75,  23,  77,  16,   6,  89,  30,  40,  29,  60,  47,  88,
        84,  48, 200])

In [10]:
b

array([[45, 35, 84, 75],
       [68, 50, 32, 10],
       [42, 68, 42, 41],
       [88, 48, 37, 52],
       [70, 69, 82, 70],
       [91, 54, 16, 68]])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[45., 35., 84., 75.,  1.],
       [68., 50., 32., 10.,  1.],
       [42., 68., 42., 41.,  1.],
       [88., 48., 37., 52.,  1.],
       [70., 69., 82., 70.,  1.],
       [91., 54., 16., 68.,  1.]])

# np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis


In [13]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [15]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.


In [16]:
# code
e = np.array([1,1,2,2,3,3,3,4,4,5,5])

np.unique(e)

array([1, 2, 3, 4, 5])

### np.expand_dims

with the help of Numpy.expand_dims() method, we can get the expands dimesions of an array


In [17]:
# code
a

array([48, 75, 23, 77, 16,  6, 89, 30, 40, 29, 60, 47, 88, 84, 48])

In [21]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [26]:
np.expand_dims(a,axis=1)


array([[48],
       [75],
       [23],
       [77],
       [16],
       [ 6],
       [89],
       [30],
       [40],
       [29],
       [60],
       [47],
       [88],
       [84],
       [48]])

### np.where

The numpy.where() function returns the indicies of the elements in an input array where the given condition is satisfied


In [27]:
a

array([48, 75, 23, 77, 16,  6, 89, 30, 40, 29, 60, 47, 88, 84, 48])

In [29]:
# find all indices with value grater than 50
np.where(a>50)

(array([ 1,  3,  6, 10, 12, 13], dtype=int64),)

In [30]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([48,  0, 23,  0, 16,  6,  0, 30, 40, 29,  0, 47,  0,  0, 48])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis


In [31]:
# code
a

array([48, 75, 23, 77, 16,  6, 89, 30, 40, 29, 60, 47, 88, 84, 48])

In [32]:
np.argmax(a)

6

In [33]:
b

array([[45, 35, 84, 75],
       [68, 50, 32, 10],
       [42, 68, 42, 41],
       [88, 48, 37, 52],
       [70, 69, 82, 70],
       [91, 54, 16, 68]])

In [34]:
np.argmax(b,axis=0)

array([5, 4, 0, 0], dtype=int64)

In [35]:
# np.argmin
np.argmin(a)

5

### np.cumsum

numpy.cumsum() function is used where we want to compute the cumulative sum of array elements over a given axis


In [36]:
# code
a

array([48, 75, 23, 77, 16,  6, 89, 30, 40, 29, 60, 47, 88, 84, 48])

In [37]:
np.cumsum(a)

array([ 48, 123, 146, 223, 239, 245, 334, 364, 404, 433, 493, 540, 628,
       712, 760])

In [38]:
b

array([[45, 35, 84, 75],
       [68, 50, 32, 10],
       [42, 68, 42, 41],
       [88, 48, 37, 52],
       [70, 69, 82, 70],
       [91, 54, 16, 68]])

In [39]:
np.cumsum(b,axis=0)

array([[ 45,  35,  84,  75],
       [113,  85, 116,  85],
       [155, 153, 158, 126],
       [243, 201, 195, 178],
       [313, 270, 277, 248],
       [404, 324, 293, 316]])

In [40]:
# np.cumprod
np.cumprod(a)

array([         48,        3600,       82800,     6375600,   102009600,
         612057600, -1361448448,  2106219520, -1650565120,  -621748224,
        1349812224,  -983334912,  -634126336, -1727004672, -1291845632])

### np.percentile

numpy.percentile() function used to compute the nth percentile of the given data(array)


In [41]:
a

array([48, 75, 23, 77, 16,  6, 89, 30, 40, 29, 60, 47, 88, 84, 48])

In [42]:
np.percentile(a,100)

89.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.


In [43]:
# code
a

array([48, 75, 23, 77, 16,  6, 89, 30, 40, 29, 60, 47, 88, 84, 48])

In [44]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 2, 1, 4, 0, 1, 2, 3, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef

Return Pearson product-moment correlation coefficients.


In [46]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary , experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

with the help of numpy.isin() method, we can see that one array having vlues are checked in a different numpy array having different elements with different sizes


In [47]:
# code
a

array([48, 75, 23, 77, 16,  6, 89, 30, 40, 29, 60, 47, 88, 84, 48])

In [50]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([30, 40, 60])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array


In [51]:
a

array([48, 75, 23, 77, 16,  6, 89, 30, 40, 29, 60, 47, 88, 84, 48])

In [52]:
np.flip(a)

array([48, 84, 88, 47, 60, 29, 40, 30, 89,  6, 16, 77, 23, 75, 48])

In [53]:
np.flip(b)

array([[68, 16, 54, 91],
       [70, 82, 69, 70],
       [52, 37, 48, 88],
       [41, 42, 68, 42],
       [10, 32, 50, 68],
       [75, 84, 35, 45]])

### np.put

The numpy.put function replaces specific elements of an array with given values of p array. Array indexed works on flattened array.


In [55]:
# code
a

array([48, 75, 23, 77, 16,  6, 89, 30, 40, 29, 60, 47, 88, 84, 48])

In [57]:
np.put(a,[0,1],[110,530])
a

array([110, 530,  23,  77,  16,   6,  89,  30,  40,  29,  60,  47,  88,
        84,  48])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis


In [58]:
a

array([110, 530,  23,  77,  16,   6,  89,  30,  40,  29,  60,  47,  88,
        84,  48])

In [59]:
np.delete(a,0)

array([530,  23,  77,  16,   6,  89,  30,  40,  29,  60,  47,  88,  84,
        48])

### set functions
+ np.union1d
+ np.intersect1d
+ np.setdiff1d
+ np.setxor1d
+ np.in1d


In [61]:
m = np.array([1,22,3,56])
n = np.array([3,4,5,6])

np.union1d(m,n)

array([ 1,  3,  4,  5,  6, 22, 56])

In [62]:
np.intersect1d(m,n)

array([3])

In [63]:
np.setdiff1d(m,n)

array([ 1, 22, 56])

In [64]:
np.setxor1d(m,n)

array([ 1,  4,  5,  6, 22, 56])

In [65]:
np.in1d(m,1)

array([ True, False, False, False])

### np.clip
numpy clip() function is used to clip(limit) the value in an array

In [66]:
# code
a

array([110, 530,  23,  77,  16,   6,  89,  30,  40,  29,  60,  47,  88,
        84,  48])

In [67]:
np.clip(a,a_min=25 , a_max=75)

array([75, 75, 25, 75, 25, 25, 75, 30, 40, 29, 60, 47, 75, 75, 48])