### What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences
+ NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

+ The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

+ NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

+ A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np
a = np.array([1,2,3])
print(type(a))  # 1D or vector

<class 'numpy.ndarray'>


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)    # matrix

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(type(c))
c   # tensor

<class 'numpy.ndarray'>


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
# dtype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [12]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
# with reshape
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# np.random
np.random.random((3,4))

array([[0.59020485, 0.29293482, 0.68028669, 0.21183684],
       [0.56647226, 0.06673625, 0.9225825 , 0.49122873],
       [0.41631059, 0.16953147, 0.39539207, 0.64612551]])

In [17]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [18]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [22]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
# ndim
a3.ndim

3

In [30]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
# size
a1.size

10

In [36]:
# itemsize
a2.itemsize

8

In [38]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [41]:
# astype
a3.dtype
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
# Scalar operations
a1 * 2

# arithmetic operation

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [61]:
# relational 
a2 == a1

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [59]:
# vector operations
# arithmetic
a1 ** a2 

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

### Array Functions

In [62]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[83., 26., 73.],
       [ 1., 49., 95.],
       [ 2., 24., 86.]])

In [65]:
# max/min/sum/prod
# 0-> col and 1-> row
np.prod(a1)
np.max(a1,axis=0)

array([83., 49., 95.])

In [67]:
# mean/median/std/var
np.median(a1)

49.0

In [68]:
# trignometric functions
np.sin(a1)

array([[ 0.96836446,  0.76255845, -0.67677196],
       [ 0.84147098, -0.95375265,  0.68326171],
       [ 0.90929743, -0.90557836, -0.92345845]])

In [72]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [73]:
# log and exponents
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [78]:
# round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[ 1., 73., 80.],
       [85., 35., 57.]])

### Indexing and slicing

In [80]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
# Indexing

In [ ]:
# 1D array
a1[-1]
a1[0]

0

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 2D Array
a2[1,2]  # 6
a2[2,3]  # 11
a2[1,0]  # 4

4

In [89]:
# 3D
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [95]:
a3[1,0,1] # 5
a3[0,1,0] # 2
a3[0,0,0] # 0
a3[1,1,0] # 6

6

In [96]:
# slicing

In [97]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
a1[2:6:2]

array([2, 4])

In [101]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]  # 0,1,2,3
a2[:,2]  # 2,6,10
a2[1:,1:3] # 5,6  , 9,10
a2[::2,::3] # 0,3 , 8,11
a2[::2,1::2] # 1,3 ,9,11
a2[1,0::3]   # 4,7
a2[0:2,1::]  # 1,2,3 ,5,6,7


array([[1, 2, 3],
       [5, 6, 7]])

In [113]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [115]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [116]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [117]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [119]:
a3[0,1,:]

array([3, 4, 5])

In [120]:
a3[1,:,1]

array([10, 13, 16])

In [121]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [122]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [123]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [126]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [127]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [128]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [129]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [130]:
# reshape

In [132]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [134]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [139]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [141]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [142]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [143]:

a4# horizontal splitting


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [147]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [148]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]