### What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences
+ NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

+ The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

+ NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

+ A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [2]:
# np.array
import numpy as np
a = np.array([1,2,3])
print(type(a))  # 1D or vector



<class 'numpy.ndarray'>


In [3]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)    # matrix

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(type(c))
c   # tensor

<class 'numpy.ndarray'>


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
# dtype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [6]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
# np.ones and np.zeros
np.ones((3,4))   # Use case in Neural Networks like intialize array in weights

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# np.random   # between o and 1 # two randoms coz class name is random and the method inside the class is also random
np.random.random((3,4))

array([[0.70682036, 0.61208997, 0.05418375, 0.22444909],
       [0.34228865, 0.04856104, 0.89901401, 0.87910065],
       [0.00762416, 0.57475509, 0.65540259, 0.00785903]])

In [11]:
# np.linspace  # lineraly space . it genrates the point at equal distance # use case in ml algorithm result where we plot some graph
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
# np.identity  # diagonal item is 1 and rest are zeros
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In NumPy, we pass shape as a tuple (e.g., (3,4)) to functions like zeros, ones, and random because shape is a single argument representing dimensions

numpy is the library, ndarray is a class inside it, and np.array([...]) gives you an object (your NumPy array).

### Array Attributes
Array attributes are the built-in properties of a NumPy array object (of class ndarray) that tell you details like its shape, size, dimensions, data type, etc.

In [13]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [14]:
# ndim   # tells the dimension of given array
a3.ndim

3

In [15]:
# shape  -> tells you the size of the array in each dimension.  -> (2,2,2) -> the frist 2 represent how many 2d array is present inside the 3d array and next (2,2) represent the spape of 2d arrays
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
# size  -> no of items
a1.size

10

In [17]:
# itemsize  -> tells how many bytes each element in the array takes in memory.
a1.itemsize

8

In [18]:
# dtype -> tells the data type of each item
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int64
float64
int64


### Changing Datatype

In [19]:
# astype -> change the data type use in memory optimize
# It just returns a new array with the new data type.
a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
# Scalar operations
a1 * 2 # 2 is a scaler and a1 is a matrix

# arithmetic operation

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [22]:
# relational -> check item by item
a2 == 13

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
# vector operations -> apply on two numpy arrays
# arithmetic
a1 ** a2    

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [71]:
a1 = np.round(np.random.random((3,3))*100)

a1

array([[62., 99., 72.],
       [50., 80., 88.],
       [98., 14., 62.]])

In [25]:
# max/min/sum/prod
# 0-> col and 1-> row
np.prod(a1)
np.sum(a1)
np.min(a1,axis=1)

array([17., 18., 42.])

In [26]:
# mean/median/std/var
np.median(a1,axis=1)

array([26., 40., 57.])

In [27]:
# trignometric functions
np.sin(a1)

array([[ 0.76255845,  0.56610764, -0.96139749],
       [-0.75098725,  0.74511316, -0.57338187],
       [ 0.43616476, -0.38778164, -0.91652155]])

In [28]:
# dot product -> row of first matrix == column of second matrix
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [29]:
# log and exponents
np.exp(a1)
np.log(a1)

array([[3.25809654, 4.33073334, 2.83321334],
       [2.89037176, 3.68887945, 4.58496748],
       [4.04305127, 4.31748811, 3.73766962]])

In [30]:
# round/floor/ceil
# round -> nearest integer par round off kar deta hai
# floor -> peache wale integer par round off kar deta hai
# ceil-> aage wale integer par round off kar deta hai
np.round(np.random.random((2,3))*100)

array([[30.,  7., 93.],
       [ 6., 15., 74.]])

### Indexing and slicing
Indexing selects one element, slicing selects a range of elements using [start:stop].

In [72]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
# Indexing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# 1D array
a1[-1]
a1[0]

np.int64(0)

In [34]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
# 2D Array
a2[1,2]  # 6
a2[2,3]  # 11
a2[1,0]  # 4

np.int64(4)

In [36]:
# 3D
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a3[1,0,1] # 5
a3[0,1,0] # 2
a3[0,0,0] # 0
a3[1,1,0] # 6

np.int64(6)

In [38]:
# slicing

In [39]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a1[2:6:2]

array([2, 4])

In [41]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2[0,:]  # 0,1,2,3
a2[:,2]  # 2,6,10
a2[1:,1:3] # 5,6  , 9,10
a2[::2,::3] # 0,3 , 8,11
a2[::2,1::2] # 1,3 ,9,11
a2[1,0::3]   # 4,7
a2[0:2,1::]  # 1,2,3 ,5,6,7


array([[1, 2, 3],
       [5, 6, 7]])

In [43]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [45]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [46]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
a3[0,1,:]

array([3, 4, 5])

In [48]:
a3[1,:,1]

array([10, 13, 16])

In [49]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [50]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [51]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [55]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [56]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [57]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [58]:
# reshape

In [59]:
# Transpose  -> intrerchange row and column
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [79]:
# ravel
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

### Stacking
use in data stacking 

In [61]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [62]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [63]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [64]:

a4# horizontal splitting


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [66]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

### Importants Points
+ A null vector (also called a zero vector) is a vector in which all elements are zero.
+ ❌ Don't use int() on a NumPy array — it expects a single number
+ ✅ Use np.astype(int) or element-wise conversion if needed
+ ✅ NumPy handles arrays — no need to convert them to Python scalars manually
+ ❗Important Point:
np.random.random() gives values between 0 and 1

When you convert these to int, all values become 0 (because int(0.56) → 0)

So the printed array will be full of 0s, and the mean will also be 0.0

+ [1:-1] → removes first and last element.

+ Used to avoid boundary values (like 0 or 1) in math/graphs.
+ c[0, :], c[-1, :] → top and bottom rows

c[:, 0], c[:, -1] → left and right columns

✅ Slicing is efficient and readable

c[[0, -1], :], c[:, [0, -1]] → fancy indexing (alternative)

❌ Cannot select all borders in one slice

✅ Use slicing for best clarity and performance

### np.title function : np.tile(array, (rows, columns))
+ rows: how many times to repeat vertically
+ columns: how many times to repeat horizontally